### ISSUE TITLE
Minor UI Issue: long names in message box

### ISSUE THREAD

**Issue by ziforigin** [bad-day/TelegramTUI#10]
In case one is using small terminal window & opens a chat\channel\whatever with somebody with very long name, the chat looks like it is presented on the screenshot below.

It might be better to check name length and in case it is longer than (10|20|?) characters to move the message under the sender's name. Or to put messages awlays under the sender's name. Or to cut names longer than (10|20|?) characters.

![2018-03-24-135739_814x463_scrot](https://user-images.githubusercontent.com/16035796/37863209-8facc880-2f6b-11e8-84a3-b0a00be97a31.png)

**Comment by bad-day** [comment]
Fixed

**Comment by ziforigin** [comment]
Resolved
