### ISSUE TITLE
'MessageFwdHeader' object has no attribute 'sender' ？

### ISSUE THREAD

**Issue by se4** [bad-day/TelegramTUI#18]
Dear bad-day,
Thank you very much for your wonder code ! I meet this problem when i run start command.

> Signed in successfully as Bi
> /usr/local/lib/python3.5/dist-packages/telethon/telegram_client.py:1369: UserWarning: get_message_history is deprecated, use get_messages instead
>   'get_message_history is deprecated, use get_messages instead'
> Traceback (most recent call last):
>   File "./telegramTUI", line 5, in <module>
>     TelegeramTUI.run()
>   File "/root/TelegramTUI/src/npyscreen/apNPSApplication.py", line 30, in run
>     return npyssafewrapper.wrapper(self.__remove_argument_call_main)
>   File "/root/TelegramTUI/src/npyscreen/npyssafewrapper.py", line 41, in wrapper
>     wrapper_no_fork(call_function)
>   File "/root/TelegramTUI/src/npyscreen/npyssafewrapper.py", line 97, in wrapper_no_fork
>     return_code = call_function(_SCREEN)    
>   File "/root/TelegramTUI/src/npyscreen/apNPSApplication.py", line 25, in __remove_argument_call_main
>     return self.main()
>   File "/root/TelegramTUI/src/npyscreen/apNPSApplicationManaged.py", line 148, in main
>     self.onStart()
>   File "/root/TelegramTUI/src/ui.py", line 13, in onStart
>     self.MainForm = self.addForm("MAIN", MainForm)
>   File "/root/TelegramTUI/src/npyscreen/apNPSApplicationManaged.py", line 55, in addForm
>     fm = FormClass( parentApp=self, *args, **keywords)
>   File "/root/TelegramTUI/src/npyscreen/fmForm.py", line 70, in __init__
>     self.create()
>   File "/root/TelegramTUI/src/MainForm.py", line 70, in create
>     self.messageBoxObj.update_messages(0)
>   File "/root/TelegramTUI/src/messageBox.py", line 27, in update_messages
>     messages = self.get_messages_info(current_user)
>   File "/root/TelegramTUI/src/messageBox.py", line 81, in get_messages_info
>     prepare_forward_message = self.prepare_forward_messages(messages[i])
>   File "/root/TelegramTUI/src/messageBox.py", line 194, in prepare_forward_messages
>     sender = fwd_from.sender
> AttributeError: 'MessageFwdHeader' object has no attribute 'sender'
>

**Comment by bad-day** [comment]
Thank you for reporting.
I made fix commit, please, try again with `git pull`.
