### ISSUE TITLE
AttributeError: 'DraftMessageEmpty' object has no attribute 'message'

### ISSUE THREAD

**Issue by vovoka** [bad-day/TelegramTUI#19]
Hi bad-day!
Thank you for the app development! 
I was trying to start it, however, met next:

> Signed in successfully as FuriKuri
> Traceback (most recent call last):
>   File "./telegramTUI", line 2, in <module>
>     from src.ui import App
>   File "/home/vk/TelegramTUI/src/ui.py", line 2, in <module>
>     from src.MainForm import MainForm
>   File "/home/vk/TelegramTUI/src/MainForm.py", line 4, in <module>
>     from src.telegramApi import client
>   File "/home/vk/TelegramTUI/src/telegramApi.py", line 200, in <module>
>     client = TelegramApi()
>   File "/home/vk/TelegramTUI/src/telegramApi.py", line 54, in __init__
>     self.dialogs = self.client.get_dialogs(limit=self.message_dialog_len)
>   File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_client.py", line 664, in get_dialogs
>     dialogs = UserList(self.iter_dialogs(*args, **kwargs))
>   File "/usr/lib/python3.5/collections/__init__.py", line 1037, in __init__
>     self.data = list(initlist)
>   File "/usr/local/lib/python3.5/dist-packages/telethon/telegram_client.py", line 645, in iter_dialogs
>     yield Dialog(self, d, entities, messages)
>   File "/usr/local/lib/python3.5/dist-packages/telethon/tl/custom/dialog.py", line 82, in __init__
>     self.draft = Draft(client, dialog.peer, dialog.draft)
>   File "/usr/local/lib/python3.5/dist-packages/telethon/tl/custom/draft.py", line 33, in __init__
>     self._text = markdown.unparse(draft.message, draft.entities)
> AttributeError: 'DraftMessageEmpty' object has no attribute 'message'

**Comment by bad-day** [comment]
Thank you for reporting, this bug has already been fixed
