### ISSUE TITLE
Can run on macOS 10.12.6

### ISSUE THREAD

**Issue by Peppuz** [bad-day/TelegramTUI#5]
I followed the installation steps, bue when I try to run `./telegramTUI` I get these errors:

```
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/telethon/telegram_client.py:1092: UserWarning: get_message_history is deprecated, use get_messages instead
  'get_message_history is deprecated, use get_messages instead'
Traceback (most recent call last):
  File "./telegramTUI", line 2, in <module>
    from src.ui import App
  File "/Users/peppuz/Tele/TelegramTUI/src/ui.py", line 8, in <module>
    from src import aalib
  File "/Users/peppuz/Tele/TelegramTUI/src/aalib.py", line 29, in <module>
    libaa = ctypes.CDLL('libaa.so.1')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(libaa.so.1, 6): image not found
```

Actually, this line
```
OSError: dlopen(libaa.so.1, 6): image not found
```
Makes me think macOS is not supported, am I right? If so, do you plan to support macOS?

Thanks in advance!

**Comment by bad-day** [comment]
Try set `aalib = False ` in *config.ini* in first time.
I think trouble in shared library, I try to fix aalib, but afraid this will be a bit problematic, because I do not have mac os

**Comment by bad-day** [comment]
Maybe `pip3 install python-aalib` can solve your problem?

**Comment by iamthen0ise** [comment]
`config=False` is not working too.

**Comment by Peppuz** [comment]
guys it was pip3 issue, closing issue.

**Comment by mattrberry** [comment]
I am having the same issue. How did you solve this?

**Comment by bad-day** [comment]
So, the [problem in the package](https://github.com/jwilk/python-aalib/issues/3) "python-aalib" for mac os.
I made a small patch that disables aalib
