### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by ziforigin** [bad-day/TelegramTUI#9]
To install whis app on system like Arch you need to install aalib:
`sudo pacman -S aalib`
or you'll get an error OSError: libaa.so.1 no such file or directory

and you need to have python image library (pillow):
`sudo pip install pillow`

**Comment by ziforigin** [comment]
Typo in config.ini:
```
# ASCII iamge art
aalib = False
```

**Comment by bad-day** [comment]
I think `aalib` depends by `python-aalib`.
Anyway, documentation is updated

**Comment by ziforigin** [comment]
Resolved
